import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { TrendingUp, Globe, AlertTriangle, ArrowRight } from "lucide-react";
import { INITIAL_USER } from "@/lib/mockData";

export default function Invest() {
  const recommendations = [
    {
      country: "USA",
      name: "S&P 500 ETF (VOO)",
      type: "Index Fund",
      risk: "Moderate",
      return: "+10.5%",
      desc: "Broad exposure to large-cap US equities.",
      match: 98
    },
    {
      country: "India",
      name: "NIFTY 50 Index",
      type: "Growth Fund",
      risk: "High",
      return: "+14.2%",
      desc: "Top 50 companies listed on National Stock Exchange.",
      match: 85
    },
    {
      country: "UK",
      name: "FTSE 100 Dividend",
      type: "Income Fund",
      risk: "Low",
      return: "+4.8%",
      desc: "Blue-chip UK companies with strong dividend history.",
      match: 70
    },
    {
      country: "Singapore",
      name: "STI ETF",
      type: "REITs Focus",
      risk: "Moderate",
      return: "+6.1%",
      desc: "Singapore straits times index with high REIT exposure.",
      match: 60
    }
  ];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Global Investment Engine</h1>
        <p className="text-muted-foreground">AI-curated opportunities based on your {INITIAL_USER.score.hybrid} hybrid score and risk profile.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {recommendations.map((item, i) => (
            <Card key={i} className="bg-card/40 backdrop-blur-md border-white/5 hover:border-primary/50 transition-all duration-300 group hover:-translate-y-1">
                <CardHeader>
                    <div className="flex justify-between items-start">
                        <Badge variant="outline" className="mb-2 border-white/10 bg-white/5 text-xs font-normal">
                            <Globe className="w-3 h-3 mr-1" /> {item.country}
                        </Badge>
                        <span className="text-xs font-mono text-emerald-400">{item.return} YoY</span>
                    </div>
                    <CardTitle className="text-lg group-hover:text-primary transition-colors">{item.name}</CardTitle>
                    <CardDescription>{item.type}</CardDescription>
                </CardHeader>
                <CardContent>
                    <p className="text-sm text-muted-foreground mb-4 min-h-[40px]">{item.desc}</p>
                    
                    <div className="flex items-center justify-between mt-4">
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase tracking-wider text-muted-foreground">Risk Level</span>
                            <span className={`text-sm font-medium ${item.risk === 'High' ? 'text-amber-500' : 'text-blue-400'}`}>
                                {item.risk}
                            </span>
                        </div>
                        <div className="flex flex-col text-right">
                            <span className="text-[10px] uppercase tracking-wider text-muted-foreground">AI Match</span>
                            <span className="text-sm font-bold text-white">{item.match}%</span>
                        </div>
                    </div>
                    
                    <Button className="w-full mt-6 bg-white/5 hover:bg-white/10 border border-white/10 text-white" size="sm">
                        View Details <ArrowRight className="w-4 h-4 ml-2" />
                    </Button>
                </CardContent>
            </Card>
        ))}
      </div>
      
      <div className="p-4 rounded-lg border border-amber-500/20 bg-amber-500/10 flex gap-3 items-start">
        <AlertTriangle className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
        <div className="text-sm text-amber-200/80">
            <strong>Disclaimer:</strong> Investment values can go up as well as down. The suggestions above are generated by our AI model based on historical data and your current credit profile. This does not constitute financial advice.
        </div>
      </div>
    </div>
  );
}
